#
# This file contains configuration flags to customize your site
#

# Basic information
name: Ian Glen
firstName: Ian
lastName: Glen
gender: Male
description: A college freshman by day, electronics hacker, maker, and developer by night.
landingDescription: A college freshman by day, <b>electronics hacker</b>, <b>maker</b>, and <b>developer</b> by night.
jobTitle: Hacker, Maker, Developer
email: ian@ianglen.me

# Site Title
title: ian<b>glen</b>

# Site Navigation
links:
- {name: Blog, url: /blog/}
- {name: Projects, url: /projects/}
- {name: Misc., url: /misc/}
- {name: Github, url: "https://github.com/codeThatThinks"}
- {name: Email, url: "mailto:ian@ianglen.me"}

# Pagination
paginate: 5
paginate_path: "/blog/:num/"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-30140370-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://ianglen.me

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# set default layout to post
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
