#
# This file contains configuration flags to customize your site
#

# Basic information
name: Ian Glen
description: EE student. Almost always working on cars, quads, or electronics.

# Site Navigation
links:
- {name: Home, url: /}
- {name: Projects, url: /projects/}
- {name: Other Stuff, url: /other/}
- {name: Github, url: "https://github.com/codeThatThinks"}
- {name: Email, url: "mailto:ian@ianglen.me"}

# Used for Sitemap.xml and your RSS feed
url: http://ianglen.me

permalink: /blog/:title/

defaults:
    -
      scope:
        path: ""
      values:
        layout: "post"

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

gfm_quirks: paragraph_end
strict_front_matter: true

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
